backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Artículos Legales"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Inmobiliario", "Civil", "Administrativo", "Doctrina"] }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Resumen", name: "summary", widget: "text" }
      - { label: "Cuerpo del Artículo", name: "body", widget: "markdown" }
