backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Artículos Legales"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título del Artículo", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { 
          label: "Materia / Categoría", 
          name: "category", 
          widget: "select", 
          options: ["inmobiliario", "civil", "constitucional", "laboral", "otros"],
          default: "inmobiliario"
        }
      - { label: "Resumen Breve", name: "summary", widget: "text", help: "Un breve párrafo que aparecerá en la tarjeta de la página principal" }
      - { label: "Contenido del Artículo", name: "body", widget: "markdown" }
